### ISSUE TITLE
🐛 Empty args causes vm to panic

### ISSUE THREAD

**Issue by mariocao** [sedaprotocol/seda-wasm-vm#16]
## 🐛 Bug Report

Calling the wasm vm without args makes it panic.

If more information is needed, @gluax can provide more information 😊 .

**Comment by gluax** [comment]
![image](https://github.com/user-attachments/assets/77aebd94-4cf8-442a-8fcd-7b42b95e40c1)

A screenshot for more context.

This does not fail on the rust side, it's how we pass this info to `c` from `go` that causes the issue.

![image](https://github.com/user-attachments/assets/894968ba-c02f-4672-a015-2a63eabd44f5)

These indexes seem to be the issue
